---
- name: EC2 document pool
  hosts: aws-document-pool
  sudo: yes 
  remote_user: ubuntu
  vars_files:
    - aws.yml
  vars:
    fyler_node_name: fyler_document_pool
    fyler_server_name: "fyler_server@{{ hostvars['fyler.teachbase.ru']['ansible_eth0']['ipv4']['address'] }}"
    fyler_role: pool
    fyler_category: document
    fyler_max_active: 5
    fyler_force_clean: false
  gather_facts: True
  roles:
    - { role: 'palkan.common_setup', tags: ['common'] }
    - { role: 'palkan.deploy_user', tags: ['user'] }
    - { role: 'palkan.erlang', tags: ['erlang'] }
    - { role: 'palkan.aws_cli', tags: ['aws_cli'] }
    - { role: unoconv, tags: ['unoconv'] }
    - { role: swftools, tags: ['swftools'] }
    - { role: fyler_deps, tags: ['fyler_deps'] }
    - { role: fyler_prepare, tags: ['app_setup'] }