---
- name: EC2 video pool
  hosts: aws-video-pool
  sudo: yes 
  remote_user: ubuntu
  vars_files:
    - aws.yml
  vars:
    fyler_node_name: fyler_video_pool
    fyler_server_name: "fyler_server@{{ hostvars['fyler.teachbase.ru']['ansible_eth0']['ipv4']['address'] }}"
    fyler_role: pool
    fyler_category: video
    fyler_force_clean: false
  gather_facts: True
  roles:
    - { role: 'palkan.common_setup', tags: ['common'] }
    - { role: 'palkan.deploy_user', tags: ['user'] }
    - { role: 'palkan.erlang', tags: ['erlang'] }
    - { role: 'palkan.aws_cli', tags: ['aws_cli'] }
    - { role: 'palkan.ffmpeg', tags: ['ffmpeg'] }
    - { role: fyler_deps, tags: ['fyler_deps'] }
    - { role: fyler_prepare, tags: ['app_setup'] }