---
- name: EC2 server
  hosts: aws-server
  sudo: yes 
  remote_user: ubuntu
  vars_files:
    - aws.yml
  vars:
    fyler_node_name: fyler_server
    fyler_server_name: "fyler_server@{{ hostvars['fyler.teachbase.ru']['ansible_eth0']['ipv4']['address'] }}"
    fyler_role: server
    fyler_category: server
    fyler_force_clean: false
  gather_facts: True
  roles:
    - { role: 'palkan.common_setup', tags: ['common'] }
    - { role: 'palkan.deploy_user', tags: ['user'] }
    - { role: 'palkan.erlang', tags: ['erlang'] }
    - { role: 'palkan.aws_cli', tags: ['aws_cli'] }
    - { role: 'palkan.postgresql', tags: ['postgres'] }
    - { role: fyler_prepare, tags: ['app_setup'] }
