---
- name: EC2 server
  hosts: aws-server
  sudo: yes 
  remote_user: ubuntu
  vars_files:
    - aws.yml
  vars:
    fyler_node_name: fyler_server
    fyler_server_name: "fyler_server@{{ hostvars['fyler.teachbase.ru']['ansible_eth0']['ipv4']['address'] }}"
    fyler_role: server
    fyler_category: server
    fyler_force_clean: false
  gather_facts: True
  roles:
    - { role: common_setup, tags: ['initial'] }
    - { role: deploy_user, tags: ['user'] }
    - { role: postgres, tags: ['postgres'] }
    - { role: erlang, tags: ['erlang'] }
    - { role: aws_cli, tags: ['aws_cli'] }
    - { role: fyler_prepare, tags: ['app_setup'] }
