---
- name: EC2 video pool
  hosts: aws-video-pool
  sudo: yes 
  remote_user: ubuntu
  vars_files:
    - group_vars/production.yml
    - aws.yml
  vars:
    fyler_node_name: fyler_video_pool
    fyler_server_name: "fyler_server@{{ hostvars['fyler.teachbase.ru']['ansible_eth0']['ipv4']['address'] }}"
    fyler_role: pool
    fyler_category: video
    fyler_force_clean: false
  gather_facts: True
  roles:
    - common_setup
    - deploy_user
    - erlang
    - aws_cli
    - fyler_deps
    - ffmpeg
    - fyler_prepare
