---
- name: Development setup
  hosts: development
  user: vagrant
  sudo: true
  vars_files:
    - group_vars/development.yml
    - aws.yml
  vars:
    fyler_force_clean: false
  roles:
    - common_setup
    - erlang
    - aws_cli
    - ffmpeg
    - unoconv
    - swftools
    - fyler_deps