- name: clone latest speex
  git: repo=git://git.xiph.org/speex.git accept_hostkey=true dest={{ ffmpeg_source_dir }}/speex

- name: compile libspeex
  shell: 'cd {{ ffmpeg_source_dir }}/speex; {{ item }} creates={{ ffmpeg_build }}/lib/libspeex.a'
  with_items:
    - autogen.sh
    - ./configure --prefix={{ ffmpeg_build }} --disable-shared
    - make
    - make install
    - make distclean
