- name: clone latest yasm
  git: repo=git://github.com/yasm/yasm.git accept_hostkey=true dest={{ ffmpeg_source_dir }}/yasm

- name: compile yasm 
  command: $item chdir={{ ffmpeg_source_dir }}/yasm creates={{ ffmpeg_bin_dir }}/yasm
  with_items:
    - ./autogen.sh
    - ./configure --prefix={{ ffmpeg_build }} --bindir={{ ffmpeg_bin_dir }}
    - make
    - make install
    - make distclean