- name: Unoconv | Create unoconv service
  action: template src=unoconvd dest=/etc/init.d/unoconvd mode=755
 
- name: Unoconv | Init service
  command: 'update-rc.d  unoconvd defaults'
 
- name: Unocnv | Restart unoconv
  action: service name=unoconvd state=running